apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
data:
    token: ${base64encode(hcloud_token)}
    network: ${base64encode(hcloud_network)}

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: hcloud-ccm
    namespace: kube-system
spec:
    repo: https://charts.hetzner.cloud
    chart: hcloud-cloud-controller-manager
    version: "1.19.0"
    bootstrap: true
    targetNamespace: kube-system
    valuesContent: |-
        networking:
          enabled: true
          clusterCIDR: 10.42.0.0/16

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: hcloud-csi
    namespace: kube-system
spec:
    repo: https://charts.hetzner.cloud
    chart: hcloud-csi
    version: "2.6.0"
    targetNamespace: kube-system
    valuesContent: ""
