apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: hcloud-ccm
    namespace: kube-system
spec:
    repo: https://charts.hetzner.cloud
    chart: hcloud-cloud-controller-manager
    version: "1.19.0"
    targetNamespace: kube-system
    valuesContent: |-
        env:
          NODE_NAME:
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          HCLOUD_TOKEN:
            value: "${hcloud_token}"
        networking:
          enabled: true
          clusterCIDR: 10.42.0.0/16
          network:
            value: "${hcloud_network}"
