apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: cluster-autoscaler
    namespace: kube-system
spec:
    repo: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    version: "9.34.0"
    targetNamespace: kube-system
    valuesContent: |-
        cloudProvider: hetzner
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - keey: node-role.kubernetes.io/master
                      operator: Exists
        extraEnv:
          HCLOUD_IMAGE: "${hcloud_image}"
          HCLOUD_TOKEN: "${hcloud_token}"
          HCLOUD_NETWORK: "${hcloud_network}"
          HCLOUD_SSH_KEY: "${hcloud_ssh_key}"
        autoscalingGroups:
        %{ for key, val in pools }
          - name: "${val.type}:${val.location}:${name}-pool-${key}"
            minSize: ${val.min_size}
            maxSize: ${val.max_size}
        %{ endfor }
