apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: hcloud-csi
    namespace: kube-system
spec:
    repo: https://charts.hetzner.cloud
    chart: hcloud-csi
    version: "2.6.0"
    targetNamespace: kube-system
    valuesContent: |-
        controller:
          hcloudToken:
            value: "${hcloud_token}"
